plugins {
    id 'java-library'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'tools.jackson.core:jackson-databind'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation testFixtures(project(':common'))
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation project(':api-call-quota')
    implementation project(':gbis-client')
}
