plugins {
    id 'java'
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':forecasting')
    implementation project(':common')
    implementation 'org.springframework:spring-jdbc'
    implementation 'tools.jackson.core:jackson-databind'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation project(':observations')
    testImplementation 'org.flywaydb:flyway-core'
    testRuntimeOnly 'org.flywaydb:flyway-database-postgresql'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

springBoot {
    mainClass = 'com.gustler.backend.maintenance.MaintenanceApplication'
}

tasks.named('test') {
    useJUnitPlatform()
}
