plugins {
    id 'java-library'
}

dependencies {
    implementation 'org.springframework:spring-tx'
    implementation 'org.slf4j:slf4j-api'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'ch.qos.logback:logback-classic'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
